### ISSUE TITLE
Problems inside Docker

### ISSUE THREAD

**Issue by AlexvEngelen** [zachleat/performance-leaderboard#21]
Hi,

I have the following error when using this package inside a Docker container.
`(Site 1 of 1, run 1 of 1): https://google.nl
Logged an error with https://google.nl:  TypeError: Cannot read property 'score' of undefined
    at ResultLogger.mapResult (/app/node_modules/performance-leaderboard/src/ResultLogger.js:237:56)
    at runLighthouse (/app/node_modules/performance-leaderboard/performance-leaderboard.js:88:37)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /app/src/index.js:113:30
[
  {
    url: 'https://google.nl',
    error: '{}',
    sidequests: {
      '-weight.total': 1,
      '+weight.total': 1,
      '-weight.document': 1,
      '+weight.document': 1,
      '-weight.script': 1,
      '+weight.script': 1,
      '-weight.image': 1,
      '+weight.image': 1,
      '-weight.font': 1,
      '+weight.font': 1,
      '+weight.fontCount': 1,
      '-timeToFirstByte': 1,
      '-totalBlockingTime': 1,
      '-largestContentfulPaint': 1
    }
  }
]`

My code is:
`(async function() {

            let urls = [
                "https://google.nl",
            ];

            const options = {
                //axePuppeteerTimeout: 120000, // 120 seconds
                writeLogs: false, // Store audit data
                readFromLogDirectory: false, // Skip tests with existing logs
                onlyCategories: ["performance"],
                chromeFlags: [
                    '--headless',
                    '--disable-gpu',
                    '--disable-dev-shm-usage',
                    '--no-first-run'
                ],
            }

            try {
                const data = await PerfLeaderboard(urls, 1, options);
                console.log(data);
            } catch (error) {
                console.log(error);
            }

        })();`

What can this be?

**Comment by marc-bouvier** [comment]
Could it be related to https://github.com/zachleat/speedlify/issues/71 ?

It seems that `chromeFlags` are overriden by `launchOptions` which might explain the problem.

**Comment by zachleat** [comment]
This is likely resolved with speedlify2!

https://www.speedlify.dev/ 
https://github.com/zachleat/speedlify2
